---
- name: Sauvegarde de la base de données MySQL depuis Docker Swarm
  hosts: app_vms
  vars:
    mysql_user: root
    mysql_password: root
    mysql_database: expense_manager
    backup_dir: "/home/{{ ansible_ssh_user }}/sauvegardes_mysql"
    backup_filename: "sauvegarde_mysql_{{ ansible_date_time.date }}.sql"
    service_name: expense-manager_db

  tasks:
    - name: S'assurer que le répertoire de sauvegarde existe
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Trouver le conteneur MySQL en cours d'exécution
      shell: >
        docker ps --filter name={{ service_name }} --format '{% raw %}{{.Names}}{% endraw %}' | head -n1
      register: container_name

    - name: Sauvegarder la base de données MySQL
      command: >
        docker exec {{ container_name.stdout }}
        mysqldump -u{{ mysql_user }} -p{{ mysql_password }} {{ mysql_database }}
      register: mysql_backup

    - name: Enregistrer la sauvegarde dans un fichier
      copy:
        content: "{{ mysql_backup.stdout }}"
        dest: "{{ backup_dir }}/{{ backup_filename }}"
        mode: '0644'

    - name: Compresser le fichier de sauvegarde
      archive:
        path: "{{ backup_dir }}/{{ backup_filename }}"
        dest: "{{ backup_dir }}/{{ backup_filename }}.gz"
        format: gz

    - name: Supprimer le fichier de sauvegarde non compressé
      file:
        path: "{{ backup_dir }}/{{ backup_filename }}"
        state: absent