---
- name: Install Docker and configure it to run without sudo
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

- name: Install additional services on one machine
  hosts: tooling_vms
  become: yes
  tasks:
    - name: Install Java OpenJDK 17
      apt:
        name: openjdk-17-jre
        state: present
        update_cache: yes

    - name: Verify Java version
      command: java -version
      register: java_version_output
      failed_when: java_version_output.rc != 0
      changed_when: false
      check_mode: no
      ignore_errors: yes

    - name: Print Java version
      debug:
        msg: "{{ java_version_output.stdout }}"

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is started and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes

- name: Install Prometheus
  hosts: tooling_vms
  become: yes
  tasks:
    - name: Create Prometheus group
      group:
        name: prometheus
        state: present

    - name: Create Prometheus user
      user:
        name: prometheus
        group: prometheus
        create_home: no
        shell: /sbin/nologin

    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt
        remote_src: yes

    - name: Change ownership of Prometheus files
      file:
        path: /opt/prometheus-2.45.0.linux-amd64
        state: directory
        owner: prometheus
        group: prometheus
        recurse: yes

    - name: Create Prometheus data directory
      file:
        path: /opt/prometheus-2.45.0.linux-amd64/data
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0700'

    - name: Create Prometheus service file
      copy:
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/opt/prometheus-2.45.0.linux-amd64/prometheus --config.file=/opt/prometheus-2.45.0.linux-amd64/prometheus.yml --storage.tsdb.path=/opt/prometheus-2.45.0.linux-amd64/data

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

- name: Install Alertmanager
  hosts: tooling_vms
  become: yes
  tasks:
    - name: Create Alertmanager group
      group:
        name: alertmanager
        state: present

    - name: Create Alertmanager user
      user:
        name: alertmanager
        group: alertmanager
        create_home: no
        shell: /sbin/nologin

    - name: Download Alertmanager
      get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
        dest: /tmp/alertmanager.tar.gz

    - name: Extract Alertmanager
      unarchive:
        src: /tmp/alertmanager.tar.gz
        dest: /opt
        remote_src: yes

    - name: Change ownership of Alertmanager files
      file:
        path: /opt/alertmanager-0.26.0.linux-amd64
        state: directory
        owner: alertmanager
        group: alertmanager
        recurse: yes

    - name: Create Alertmanager data directory
      file:
        path: /opt/alertmanager-0.26.0.linux-amd64/data
        state: directory
        owner: alertmanager
        group: alertmanager
        mode: '0700'

    - name: Create Alertmanager configuration file
      copy:
        content: |
          global:
            resolve_timeout: 5m

          route:
            receiver: 'default'

          receivers:
            - name: 'default'
        dest: /opt/alertmanager-0.26.0.linux-amd64/alertmanager.yml
        owner: alertmanager
        group: alertmanager
        mode: '0644'

    - name: Create Alertmanager service file
      copy:
        content: |
          [Unit]
          Description=Alertmanager
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=alertmanager
          Group=alertmanager
          Type=simple
          ExecStart=/opt/alertmanager-0.26.0.linux-amd64/alertmanager --config.file=/opt/alertmanager-0.26.0.linux-amd64/alertmanager.yml --storage.path=/opt/alertmanager-0.26.0.linux-amd64/data

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/alertmanager.service
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Alertmanager service
      systemd:
        name: alertmanager
        state: started
        enabled: yes

- name: Install Grafana
  hosts: tooling_vms
  become: yes
  tasks:
    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: latest
        update_cache: yes

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

- name: Install Ansible
  hosts: tooling_vms
  become: yes
  tasks:
    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes
        